name: Docker pull to server

on:
  workflow_call:
    secrets:
      host:
        description: "Host for SSH"
      username:
        description: "Username for SSH"
      password:
        description: "Password for SSH"
      port:
        description: "Port for SSH"
      server_name:
        description: "Server name"
      tg_token:
        description: "TG token"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          command_timeout: 10m
          script: |
            set -e
            cd /root/eventlab
            docker compose pull stream-chat-server
            docker compose up -d --no-deps stream-chat-server
            sleep 5
            docker ps --filter "name=stream-chat-server" --format "{{.Status}}" | grep -q "Up" || (echo "Container is not running" && exit 1)
            docker image prune -af
